# Shared helpers and vocab for the minimal open-source pipeline.

import glob
import hashlib
import os
import re
from typing import Iterable, List, Sequence


_INT_RE = re.compile(r"(\\d+)")


def expand_input_paths(paths: Sequence[str]) -> List[str]:
    """
    Expand local filesystem inputs.

    Supported:
    - file path
    - directory (all files under it)
    - glob pattern (e.g. /data/*.parquet)

    Not supported:
    - HDFS / other remote schemes
    """
    out: List[str] = []
    for p in paths:
        if p.startswith("hdfs:") or p.startswith("hdfs://"):
            raise ValueError(f"HDFS paths are not supported in open-source mode: {p}")

        if any(ch in p for ch in "*?[]"):
            out.extend(glob.glob(p))
            continue

        if os.path.isdir(p):
            for name in os.listdir(p):
                out.append(os.path.join(p, name))
            continue

        out.append(p)

    out = [x for x in out if os.path.isfile(x) and x.endswith(".parquet")]
    out.sort()
    return out


def _stable_shard_key(path: str) -> int:
    # Prefer an integer in the filename if present (helps reproduce legacy sharding patterns),
    # otherwise fall back to a stable hash.
    base = os.path.basename(path)
    nums = _INT_RE.findall(base)
    if nums:
        return int(nums[-1])
    return int(hashlib.md5(path.encode("utf-8")).hexdigest(), 16)


def filter_paths_for_shard(
    paths: Sequence[str],
    *,
    node_index: int,
    node_num: int,
    chunk_index: int,
    chunk_num: int,
) -> List[str]:
    mod = max(1, node_num * chunk_num)
    target = (node_index * chunk_num + chunk_index) % mod
    return [p for p in paths if (_stable_shard_key(p) % mod) == target]


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)



def expand_box_by_ratio(box, ratio):
    x, y = (box[0]+box[2]) / 2, (box[1]+box[3]) / 2
    w, h = box[2]-box[0], box[3]-box[1]

    return [x - w * ratio / 2, y - h * ratio / 2, x + w * ratio / 2, y + h * ratio / 2]

def boxes_overlap(box1, box2):
    box1 = expand_box_by_ratio(box1, 2.5)
    box2 = expand_box_by_ratio(box2, 2.5)
    """ Check if two boxes (x_min, y_min, x_max, y_max) overlap. """
    return not (box1[2] < box2[0] or box1[0] > box2[2] or box1[3] < box2[1] or box1[1] > box2[3])

def find_disjoint_connected_sets(boxes):
    """ Find all disjoint sets of connected boxes, represented by their original indices. """
    disjoint_sets = []
    visited = set()

    def dfs(current_index, current_set):
        for i, (_, box) in enumerate(boxes):
            if i not in visited and boxes_overlap(boxes[current_index][1], box):
                visited.add(i)
                current_set.append(boxes[i][0])  # Store the original index
                dfs(i, current_set)

    for i in range(len(boxes)):
        if i not in visited:
            visited.add(i)
            current_set = [boxes[i][0]]  # Store the original index
            dfs(i, current_set)
            disjoint_sets.append(current_set)
    
    return disjoint_sets

def group_boxes_by_tag(boxes, names):
    """ Group boxes by name tags and find disjoint connected sets for each tag, using original indices. """
    tag_to_disjoint_sets = {}
    # Create a list of tuples (original index, box)
    indexed_boxes = list(enumerate(boxes))

    # Group boxes by name tags along with their original indices
    for index, (name, box) in enumerate(zip(names, boxes)):
        tag_to_disjoint_sets.setdefault(name, []).append((index, box))

    # Find disjoint connected sets for each tag
    for tag in tag_to_disjoint_sets:
        tag_to_disjoint_sets[tag] = find_disjoint_connected_sets(tag_to_disjoint_sets[tag])

    return tag_to_disjoint_sets

# Example usage
# names = ["tag1", "tag1", "tag2", "tag3", "tag1", "tag1", "tag1"]
# boxes = [(10, 10, 20, 20), (15, 15, 25, 25), (30, 30, 40, 40), (35, 35, 45, 45), (22, 22, 32, 32), (100, 100, 110, 110), (105, 105, 115, 115)]

# grouped_boxes = group_boxes_by_tag(boxes, names)
# for tag, disjoint_sets in grouped_boxes.items():
#     print(f"{tag}: {disjoint_sets}")


class_to_objects = {
    "people": ["Man", "Woman", "Child", "Teenager", "Adult", "Elderly", "Athlete", "Worker", "Student"],
    "vehicles": ["Car", "Bicycle", "Motorcycle", "Bus", "Truck", "Airplane", "Boat", "Train", "Scooter"],
    "animals": ["Dog", "Cat", "Bird", "Fish", "Horse", "Cow", "Sheep", "Lion", "Elephant", "Bear"],
    "furniture": ["Chair", "Table", "Bed", "Sofa", "Cabinet", "Desk", "Shelf", "Dresser", "Couch"],
    "electronics": ["Computer", "Smartphone", "Television", "Camera", "Headphones", "Speaker", "Microwave", "Refrigerator", "Washing Machine"],
    "clothing": ["Shirt", "Pants", "Dress", "Skirt", "Jacket", "Hat", "Shoes", "Coat", "Sweater"],
    "fruits": ["Apple", "Banana", "Orange", "Grapes", "Pear", "Cherry", "Strawberry", "Pineapple", "Mango"],
    "vegetables": ["Carrot", "Potato", "Tomato", "Lettuce", "Onion", "Cucumber", "Pepper", "Broccoli", "Spinach"],
    "tools": ["Hammer", "Screwdriver", "Wrench", "Drill", "Saw", "Pliers", "Tape Measure", "Level", "Chisel"],
    "musical instruments": ["Guitar", "Piano", "Drums", "Violin", "Trumpet", "Flute", "Saxophone", "Cello", "Harp"],
    "sports equipment": ["Soccer Ball", "Basketball", "Tennis Racket", "Baseball Bat", "Golf Club", "Skateboard", "Football", "Hockey Stick", "Swimming Goggles"],
    "kitchen utensils": ["Knife", "Fork", "Spoon", "Plate", "Cup", "Pot", "Pan", "Mixing Bowl", "Measuring Cup"],
    "office supplies": ["Pen", "Pencil", "Notebook", "Paper", "Stapler", "Calculator", "Scissors", "Tape", "Highlighter"],
    "toys": ["Doll", "Action Figure", "Puzzle", "Board Game", "Building Blocks", "Teddy Bear", "Remote Control Car", "Yo-Yo", "Jump Rope"],
    "art supplies": ["Paintbrush", "Canvas", "Paint", "Crayons", "Markers", "Colored Pencils", "Easel", "Clay", "Sketchbook"],
    "beverages": ["Water", "Coffee", "Tea", "Soda", "Juice", "Milk", "Beer", "Wine", "Smoothie"],
    "snacks": ["Chips", "Cookies", "Candy", "Chocolate", "Popcorn", "Nuts", "Yogurt", "Granola Bar", "Fruit Snacks"],
    "personal care items": ["Toothbrush", "Toothpaste", "Shampoo", "Soap", "Deodorant", "Razor", "Lotion", "Perfume", "Hairbrush"]
}


COCO_CLASS_NAMES = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "ski",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]

LVIS_CLASS_NAMES = [
    "aerosol_can",
    "air_conditioner",
    "airplane",
    "alarm_clock",
    "alcohol",
    "alligator",
    "almond",
    "ambulance",
    "amplifier",
    "anklet",
    "antenna",
    "apple",
    "applesauce",
    "apricot",
    "apron",
    "aquarium",
    "arctic_(type_of_shoe)",
    "armband",
    "armchair",
    "armoire",
    "armor",
    "artichoke",
    "trash_can",
    "ashtray",
    "asparagus",
    "atomizer",
    "avocado",
    "award",
    "awning",
    "ax",
    "baboon",
    "baby_buggy",
    "basketball_backboard",
    "backpack",
    "handbag",
    "suitcase",
    "bagel",
    "bagpipe",
    "baguet",
    "bait",
    "ball",
    "ballet_skirt",
    "balloon",
    "bamboo",
    "banana",
    "Band_Aid",
    "bandage",
    "bandanna",
    "banjo",
    "banner",
    "barbell",
    "barge",
    "barrel",
    "barrette",
    "barrow",
    "baseball_base",
    "baseball",
    "baseball_bat",
    "baseball_cap",
    "baseball_glove",
    "basket",
    "basketball",
    "bass_horn",
    "bat_(animal)",
    "bath_mat",
    "bath_towel",
    "bathrobe",
    "bathtub",
    "batter_(food)",
    "battery",
    "beachball",
    "bead",
    "bean_curd",
    "beanbag",
    "beanie",
    "bear",
    "bed",
    "bedpan",
    "bedspread",
    "cow",
    "beef_(food)",
    "beeper",
    "beer_bottle",
    "beer_can",
    "beetle",
    "bell",
    "bell_pepper",
    "belt",
    "belt_buckle",
    "bench",
    "beret",
    "bib",
    "Bible",
    "bicycle",
    "visor",
    "billboard",
    "binder",
    "binoculars",
    "bird",
    "birdfeeder",
    "birdbath",
    "birdcage",
    "birdhouse",
    "birthday_cake",
    "birthday_card",
    "pirate_flag",
    "black_sheep",
    "blackberry",
    "blackboard",
    "blanket",
    "blazer",
    "blender",
    "blimp",
    "blinker",
    "blouse",
    "blueberry",
    "gameboard",
    "boat",
    "bob",
    "bobbin",
    "bobby_pin",
    "boiled_egg",
    "bolo_tie",
    "deadbolt",
    "bolt",
    "bonnet",
    "book",
    "bookcase",
    "booklet",
    "bookmark",
    "boom_microphone",
    "boot",
    "bottle",
    "bottle_opener",
    "bouquet",
    "bow_(weapon)",
    "bow_(decorative_ribbons)",
    "bow-tie",
    "bowl",
    "pipe_bowl",
    "bowler_hat",
    "bowling_ball",
    "box",
    "boxing_glove",
    "suspenders",
    "bracelet",
    "brass_plaque",
    "brassiere",
    "bread-bin",
    "bread",
    "breechcloth",
    "bridal_gown",
    "briefcase",
    "broccoli",
    "broach",
    "broom",
    "brownie",
    "brussels_sprouts",
    "bubble_gum",
    "bucket",
    "horse_buggy",
    "bull",
    "bulldog",
    "bulldozer",
    "bullet_train",
    "bulletin_board",
    "bulletproof_vest",
    "bullhorn",
    "bun",
    "bunk_bed",
    "buoy",
    "burrito",
    "bus_(vehicle)",
    "business_card",
    "butter",
    "butterfly",
    "button",
    "cab_(taxi)",
    "cabana",
    "cabin_car",
    "cabinet",
    "locker",
    "cake",
    "calculator",
    "calendar",
    "calf",
    "camcorder",
    "camel",
    "camera",
    "camera_lens",
    "camper_(vehicle)",
    "can",
    "can_opener",
    "candle",
    "candle_holder",
    "candy_bar",
    "candy_cane",
    "walking_cane",
    "canister",
    "canoe",
    "cantaloup",
    "canteen",
    "cap_(headwear)",
    "bottle_cap",
    "cape",
    "cappuccino",
    "car_(automobile)",
    "railcar_(part_of_a_train)",
    "elevator_car",
    "car_battery",
    "identity_card",
    "card",
    "cardigan",
    "cargo_ship",
    "carnation",
    "horse_carriage",
    "carrot",
    "tote_bag",
    "cart",
    "carton",
    "cash_register",
    "casserole",
    "cassette",
    "cast",
    "cat",
    "cauliflower",
    "cayenne_(spice)",
    "CD_player",
    "celery",
    "cellular_telephone",
    "chain_mail",
    "chair",
    "chaise_longue",
    "chalice",
    "chandelier",
    "chap",
    "checkbook",
    "checkerboard",
    "cherry",
    "chessboard",
    "chicken_(animal)",
    "chickpea",
    "chili_(vegetable)",
    "chime",
    "chinaware",
    "crisp_(potato_chip)",
    "poker_chip",
    "chocolate_bar",
    "chocolate_cake",
    "chocolate_milk",
    "chocolate_mousse",
    "choker",
    "chopping_board",
    "chopstick",
    "Christmas_tree",
    "slide",
    "cider",
    "cigar_box",
    "cigarette",
    "cigarette_case",
    "cistern",
    "clarinet",
    "clasp",
    "cleansing_agent",
    "cleat_(for_securing_rope)",
    "clementine",
    "clip",
    "clipboard",
    "clippers_(for_plants)",
    "cloak",
    "clock",
    "clock_tower",
    "clothes_hamper",
    "clothespin",
    "clutch_bag",
    "coaster",
    "coat",
    "coat_hanger",
    "coatrack",
    "cock",
    "cockroach",
    "cocoa_(beverage)",
    "coconut",
    "coffee_maker",
    "coffee_table",
    "coffeepot",
    "coil",
    "coin",
    "colander",
    "coleslaw",
    "coloring_material",
    "combination_lock",
    "pacifier",
    "comic_book",
    "compass",
    "computer_keyboard",
    "condiment",
    "cone",
    "control",
    "convertible_(automobile)",
    "sofa_bed",
    "cooker",
    "cookie",
    "cooking_utensil",
    "cooler_(for_food)",
    "cork_(bottle_plug)",
    "corkboard",
    "corkscrew",
    "edible_corn",
    "cornbread",
    "cornet",
    "cornice",
    "cornmeal",
    "corset",
    "costume",
    "cougar",
    "coverall",
    "cowbell",
    "cowboy_hat",
    "crab_(animal)",
    "crabmeat",
    "cracker",
    "crape",
    "crate",
    "crayon",
    "cream_pitcher",
    "crescent_roll",
    "crib",
    "crock_pot",
    "crossbar",
    "crouton",
    "crow",
    "crowbar",
    "crown",
    "crucifix",
    "cruise_ship",
    "police_cruiser",
    "crumb",
    "crutch",
    "cub_(animal)",
    "cube",
    "cucumber",
    "cufflink",
    "cup",
    "trophy_cup",
    "cupboard",
    "cupcake",
    "hair_curler",
    "curling_iron",
    "curtain",
    "cushion",
    "cylinder",
    "cymbal",
    "dagger",
    "dalmatian",
    "dartboard",
    "date_(fruit)",
    "deck_chair",
    "deer",
    "dental_floss",
    "desk",
    "detergent",
    "diaper",
    "diary",
    "die",
    "dinghy",
    "dining_table",
    "tux",
    "dish",
    "dish_antenna",
    "dishrag",
    "dishtowel",
    "dishwasher",
    "dishwasher_detergent",
    "dispenser",
    "diving_board",
    "Dixie_cup",
    "dog",
    "dog_collar",
    "doll",
    "dollar",
    "dollhouse",
    "dolphin",
    "domestic_ass",
    "doorknob",
    "doormat",
    "doughnut",
    "dove",
    "dragonfly",
    "drawer",
    "underdrawers",
    "dress",
    "dress_hat",
    "dress_suit",
    "dresser",
    "drill",
    "drone",
    "dropper",
    "drum_(musical_instrument)",
    "drumstick",
    "duck",
    "duckling",
    "duct_tape",
    "duffel_bag",
    "dumbbell",
    "dumpster",
    "dustpan",
    "eagle",
    "earphone",
    "earplug",
    "earring",
    "easel",
    "eclair",
    "eel",
    "egg",
    "egg_roll",
    "egg_yolk",
    "eggbeater",
    "eggplant",
    "electric_chair",
    "refrigerator",
    "elephant",
    "elk",
    "envelope",
    "eraser",
    "escargot",
    "eyepatch",
    "falcon",
    "fan",
    "faucet",
    "fedora",
    "ferret",
    "Ferris_wheel",
    "ferry",
    "fig_(fruit)",
    "fighter_jet",
    "figurine",
    "file_cabinet",
    "file_(tool)",
    "fire_alarm",
    "fire_engine",
    "fire_extinguisher",
    "fire_hose",
    "fireplace",
    "fireplug",
    "first-aid_kit",
    "fish",
    "fish_(food)",
    "fishbowl",
    "fishing_rod",
    "flag",
    "flagpole",
    "flamingo",
    "flannel",
    "flap",
    "flash",
    "flashlight",
    "fleece",
    "flip-flop_(sandal)",
    "flipper_(footwear)",
    "flower_arrangement",
    "flute_glass",
    "foal",
    "folding_chair",
    "food_processor",
    "football_(American)",
    "football_helmet",
    "footstool",
    "fork",
    "forklift",
    "freight_car",
    "French_toast",
    "freshener",
    "frisbee",
    "frog",
    "fruit_juice",
    "frying_pan",
    "fudge",
    "funnel",
    "futon",
    "gag",
    "garbage",
    "garbage_truck",
    "garden_hose",
    "gargle",
    "gargoyle",
    "garlic",
    "gasmask",
    "gazelle",
    "gelatin",
    "gemstone",
    "generator",
    "giant_panda",
    "gift_wrap",
    "ginger",
    "giraffe",
    "cincture",
    "glass_(drink_container)",
    "globe",
    "glove",
    "goat",
    "goggles",
    "goldfish",
    "golf_club",
    "golfcart",
    "gondola_(boat)",
    "goose",
    "gorilla",
    "gourd",
    "grape",
    "grater",
    "gravestone",
    "gravy_boat",
    "green_bean",
    "green_onion",
    "griddle",
    "grill",
    "grits",
    "grizzly",
    "grocery_bag",
    "guitar",
    "gull",
    "gun",
    "hairbrush",
    "hairnet",
    "hairpin",
    "halter_top",
    "ham",
    "hamburger",
    "hammer",
    "hammock",
    "hamper",
    "hamster",
    "hair_dryer",
    "hand_glass",
    "hand_towel",
    "handcart",
    "handcuff",
    "handkerchief",
    "handle",
    "handsaw",
    "hardback_book",
    "harmonium",
    "hat",
    "hatbox",
    "veil",
    "headband",
    "headboard",
    "headlight",
    "headscarf",
    "headset",
    "headstall_(for_horses)",
    "heart",
    "heater",
    "helicopter",
    "helmet",
    "heron",
    "highchair",
    "hinge",
    "hippopotamus",
    "hockey_stick",
    "hog",
    "home_plate_(baseball)",
    "honey",
    "fume_hood",
    "hook",
    "hookah",
    "hornet",
    "horse",
    "hose",
    "hot-air_balloon",
    "hotplate",
    "hot_sauce",
    "hourglass",
    "houseboat",
    "hummingbird",
    "hummus",
    "polar_bear",
    "icecream",
    "popsicle",
    "ice_maker",
    "ice_pack",
    "ice_skate",
    "igniter",
    "inhaler",
    "iPod",
    "iron_(for_clothing)",
    "ironing_board",
    "jacket",
    "jam",
    "jar",
    "jean",
    "jeep",
    "jelly_bean",
    "jersey",
    "jet_plane",
    "jewel",
    "jewelry",
    "joystick",
    "jumpsuit",
    "kayak",
    "keg",
    "kennel",
    "kettle",
    "key",
    "keycard",
    "kilt",
    "kimono",
    "kitchen_sink",
    "kitchen_table",
    "kite",
    "kitten",
    "kiwi_fruit",
    "knee_pad",
    "knife",
    "knitting_needle",
    "knob",
    "knocker_(on_a_door)",
    "koala",
    "lab_coat",
    "ladder",
    "ladle",
    "ladybug",
    "lamb_(animal)",
    "lamb-chop",
    "lamp",
    "lamppost",
    "lampshade",
    "lantern",
    "lanyard",
    "laptop_computer",
    "lasagna",
    "latch",
    "lawn_mower",
    "leather",
    "legging_(clothing)",
    "Lego",
    "legume",
    "lemon",
    "lemonade",
    "lettuce",
    "license_plate",
    "life_buoy",
    "life_jacket",
    "lightbulb",
    "lightning_rod",
    "lime",
    "limousine",
    "lion",
    "lip_balm",
    "liquor",
    "lizard",
    "log",
    "lollipop",
    "speaker_(stereo_equipment)",
    "loveseat",
    "machine_gun",
    "magazine",
    "magnet",
    "mail_slot",
    "mailbox_(at_home)",
    "mallard",
    "mallet",
    "mammoth",
    "manatee",
    "mandarin_orange",
    "manger",
    "manhole",
    "map",
    "marker",
    "martini",
    "mascot",
    "mashed_potato",
    "masher",
    "mask",
    "mast",
    "mat_(gym_equipment)",
    "matchbox",
    "mattress",
    "measuring_cup",
    "measuring_stick",
    "meatball",
    "medicine",
    "melon",
    "microphone",
    "microscope",
    "microwave_oven",
    "milestone",
    "milk",
    "milk_can",
    "milkshake",
    "minivan",
    "mint_candy",
    "mirror",
    "mitten",
    "mixer_(kitchen_tool)",
    "money",
    "monitor_(computer_equipment) computer_monitor",
    "monkey",
    "motor",
    "motor_scooter",
    "motor_vehicle",
    "motorcycle",
    "mound_(baseball)",
    "mouse_(computer_equipment)",
    "mousepad",
    "muffin",
    "mug",
    "mushroom",
    "music_stool",
    "musical_instrument",
    "nailfile",
    "napkin",
    "neckerchief",
    "necklace",
    "necktie",
    "needle",
    "nest",
    "newspaper",
    "newsstand",
    "nightshirt",
    "nosebag_(for_animals)",
    "noseband_(for_animals)",
    "notebook",
    "notepad",
    "nut",
    "nutcracker",
    "oar",
    "octopus_(food)",
    "octopus_(animal)",
    "oil_lamp",
    "olive_oil",
    "omelet",
    "onion",
    "orange_(fruit)",
    "orange_juice",
    "ostrich",
    "ottoman",
    "oven",
    "overalls_(clothing)",
    "owl",
    "packet",
    "inkpad",
    "pad",
    "paddle",
    "padlock",
    "paintbrush",
    "painting",
    "pajamas",
    "palette",
    "pan_(for_cooking)",
    "pan_(metal_container)",
    "pancake",
    "pantyhose",
    "papaya",
    "paper_plate",
    "paper_towel",
    "paperback_book",
    "paperweight",
    "parachute",
    "parakeet",
    "parasail_(sports)",
    "parasol",
    "parchment",
    "parka",
    "parking_meter",
    "parrot",
    "passenger_car_(part_of_a_train)",
    "passenger_ship",
    "passport",
    "pastry",
    "patty_(food)",
    "pea_(food)",
    "peach",
    "peanut_butter",
    "pear",
    "peeler_(tool_for_fruit_and_vegetables)",
    "wooden_leg",
    "pegboard",
    "pelican",
    "pen",
    "pencil",
    "pencil_box",
    "pencil_sharpener",
    "pendulum",
    "penguin",
    "pennant",
    "penny_(coin)",
    "pepper",
    "pepper_mill",
    "perfume",
    "persimmon",
    "person",
    "pet",
    "pew_(church_bench)",
    "phonebook",
    "phonograph_record",
    "piano",
    "pickle",
    "pickup_truck",
    "pie",
    "pigeon",
    "piggy_bank",
    "pillow",
    "pin_(non_jewelry)",
    "pineapple",
    "pinecone",
    "ping-pong_ball",
    "pinwheel",
    "tobacco_pipe",
    "pipe",
    "pistol",
    "pita_(bread)",
    "pitcher_(vessel_for_liquid)",
    "pitchfork",
    "pizza",
    "place_mat",
    "plate",
    "platter",
    "playpen",
    "pliers",
    "plow_(farm_equipment)",
    "plume",
    "pocket_watch",
    "pocketknife",
    "poker_(fire_stirring_tool)",
    "pole",
    "polo_shirt",
    "poncho",
    "pony",
    "pool_table",
    "pop_(soda)",
    "postbox_(public)",
    "postcard",
    "poster",
    "pot",
    "flowerpot",
    "potato",
    "potholder",
    "pottery",
    "pouch",
    "power_shovel",
    "prawn",
    "pretzel",
    "printer",
    "projectile_(weapon)",
    "projector",
    "propeller",
    "prune",
    "pudding",
    "puffer_(fish)",
    "puffin",
    "pug-dog",
    "pumpkin",
    "puncher",
    "puppet",
    "puppy",
    "quesadilla",
    "quiche",
    "quilt",
    "rabbit",
    "race_car",
    "racket",
    "radar",
    "radiator",
    "radio_receiver",
    "radish",
    "raft",
    "rag_doll",
    "raincoat",
    "ram_(animal)",
    "raspberry",
    "rat",
    "razorblade",
    "reamer_(juicer)",
    "rearview_mirror",
    "receipt",
    "recliner",
    "record_player",
    "reflector",
    "remote_control",
    "rhinoceros",
    "rib_(food)",
    "rifle",
    "ring",
    "river_boat",
    "road_map",
    "robe",
    "rocking_chair",
    "rodent",
    "roller_skate",
    "Rollerblade",
    "rolling_pin",
    "root_beer",
    "router_(computer_equipment)",
    "rubber_band",
    "runner_(carpet)",
    "plastic_bag",
    "saddle_(on_an_animal)",
    "saddle_blanket",
    "saddlebag",
    "safety_pin",
    "sail",
    "salad",
    "salad_plate",
    "salami",
    "salmon_(fish)",
    "salmon_(food)",
    "salsa",
    "saltshaker",
    "sandal_(type_of_shoe)",
    "sandwich",
    "satchel",
    "saucepan",
    "saucer",
    "sausage",
    "sawhorse",
    "saxophone",
    "scale_(measuring_instrument)",
    "scarecrow",
    "scarf",
    "school_bus",
    "scissors",
    "scoreboard",
    "scraper",
    "screwdriver",
    "scrubbing_brush",
    "sculpture",
    "seabird",
    "seahorse",
    "seaplane",
    "seashell",
    "sewing_machine",
    "shaker",
    "shampoo",
    "shark",
    "sharpener",
    "Sharpie",
    "shaver_(electric)",
    "shaving_cream",
    "shawl",
    "shears",
    "sheep",
    "shepherd_dog",
    "sherbert",
    "shield",
    "shirt",
    "shoe",
    "shopping_bag",
    "shopping_cart",
    "short_pants",
    "shot_glass",
    "shoulder_bag",
    "shovel",
    "shower_head",
    "shower_cap",
    "shower_curtain",
    "shredder_(for_paper)",
    "signboard",
    "silo",
    "sink",
    "skateboard",
    "skewer",
    "ski",
    "ski_boot",
    "ski_parka",
    "ski_pole",
    "skirt",
    "skullcap",
    "sled",
    "sleeping_bag",
    "sling_(bandage)",
    "slipper_(footwear)",
    "smoothie",
    "snake",
    "snowboard",
    "snowman",
    "snowmobile",
    "soap",
    "soccer_ball",
    "sock",
    "sofa",
    "softball",
    "solar_array",
    "sombrero",
    "soup",
    "soup_bowl",
    "soupspoon",
    "sour_cream",
    "soya_milk",
    "space_shuttle",
    "sparkler_(fireworks)",
    "spatula",
    "spear",
    "spectacles",
    "spice_rack",
    "spider",
    "crawfish",
    "sponge",
    "spoon",
    "sportswear",
    "spotlight",
    "squid_(food)",
    "squirrel",
    "stagecoach",
    "stapler_(stapling_machine)",
    "starfish",
    "statue_(sculpture)",
    "steak_(food)",
    "steak_knife",
    "steering_wheel",
    "stepladder",
    "step_stool",
    "stereo_(sound_system)",
    "stew",
    "stirrer",
    "stirrup",
    "stool",
    "stop_sign",
    "brake_light",
    "stove",
    "strainer",
    "strap",
    "straw_(for_drinking)",
    "strawberry",
    "street_sign",
    "streetlight",
    "string_cheese",
    "stylus",
    "subwoofer",
    "sugar_bowl",
    "sugarcane_(plant)",
    "suit_(clothing)",
    "sunflower",
    "sunglasses",
    "sunhat",
    "surfboard",
    "sushi",
    "mop",
    "sweat_pants",
    "sweatband",
    "sweater",
    "sweatshirt",
    "sweet_potato",
    "swimsuit",
    "sword",
    "syringe",
    "Tabasco_sauce",
    "table-tennis_table",
    "table",
    "table_lamp",
    "tablecloth",
    "tachometer",
    "taco",
    "tag",
    "taillight",
    "tambourine",
    "army_tank",
    "tank_(storage_vessel)",
    "tank_top_(clothing)",
    "tape_(sticky_cloth_or_paper)",
    "tape_measure",
    "tapestry",
    "tarp",
    "tartan",
    "tassel",
    "tea_bag",
    "teacup",
    "teakettle",
    "teapot",
    "teddy_bear",
    "telephone",
    "telephone_booth",
    "telephone_pole",
    "telephoto_lens",
    "television_camera",
    "television_set",
    "tennis_ball",
    "tennis_racket",
    "tequila",
    "thermometer",
    "thermos_bottle",
    "thermostat",
    "thimble",
    "thread",
    "thumbtack",
    "tiara",
    "tiger",
    "tights_(clothing)",
    "timer",
    "tinfoil",
    "tinsel",
    "tissue_paper",
    "toast_(food)",
    "toaster",
    "toaster_oven",
    "toilet",
    "toilet_tissue",
    "tomato",
    "tongs",
    "toolbox",
    "toothbrush",
    "toothpaste",
    "toothpick",
    "cover",
    "tortilla",
    "tow_truck",
    "towel",
    "towel_rack",
    "toy",
    "tractor_(farm_equipment)",
    "traffic_light",
    "dirt_bike",
    "trailer_truck",
    "train_(railroad_vehicle)",
    "trampoline",
    "tray",
    "trench_coat",
    "triangle_(musical_instrument)",
    "tricycle",
    "tripod",
    "trousers",
    "truck",
    "truffle_(chocolate)",
    "trunk",
    "vat",
    "turban",
    "turkey_(food)",
    "turnip",
    "turtle",
    "turtleneck_(clothing)",
    "typewriter",
    "umbrella",
    "underwear",
    "unicycle",
    "urinal",
    "urn",
    "vacuum_cleaner",
    "vase",
    "vending_machine",
    "vent",
    "vest",
    "videotape",
    "vinegar",
    "violin",
    "vodka",
    "volleyball",
    "vulture",
    "waffle",
    "waffle_iron",
    "wagon",
    "wagon_wheel",
    "walking_stick",
    "wall_clock",
    "wall_socket",
    "wallet",
    "walrus",
    "wardrobe",
    "washbasin",
    "automatic_washer",
    "watch",
    "water_bottle",
    "water_cooler",
    "water_faucet",
    "water_heater",
    "water_jug",
    "water_gun",
    "water_scooter",
    "water_ski",
    "water_tower",
    "watering_can",
    "watermelon",
    "weathervane",
    "webcam",
    "wedding_cake",
    "wedding_ring",
    "wet_suit",
    "wheel",
    "wheelchair",
    "whipped_cream",
    "whistle",
    "wig",
    "wind_chime",
    "windmill",
    "window_box_(for_plants)",
    "windshield_wiper",
    "windsock",
    "wine_bottle",
    "wine_bucket",
    "wineglass",
    "blinder_(for_horses)",
    "wok",
    "wolf",
    "wooden_spoon",
    "wreath",
    "wrench",
    "wristband",
    "wristlet",
    "yacht",
    "yogurt",
    "yoke_(animal_equipment)",
    "zebra",
    "zucchini",
]

ADE20K_CLASS_NAMES = [
    "wall",
    "building",
    "sky",
    "floor",
    "tree",
    "ceiling",
    "road",
    "bed",
    "windowpane",
    "grass",
    "cabinet",
    "sidewalk",
    "person",
    "earth",
    "door",
    "table",
    "mountain",
    "plant",
    "curtain",
    "chair",
    "car",
    "water",
    "painting",
    "sofa",
    "shelf",
    "house",
    "sea",
    "mirror",
    "rug",
    "field",
    "armchair",
    "seat",
    "fence",
    "desk",
    "rock",
    "wardrobe",
    "lamp",
    "bathtub",
    "railing",
    "cushion",
    "base",
    "box",
    "column",
    "signboard",
    "chest of drawers",
    "counter",
    "sand",
    "sink",
    "skyscraper",
    "fireplace",
    "refrigerator",
    "grandstand",
    "path",
    "stairs",
    "runway",
    "case",
    "pool table",
    "pillow",
    "screen door",
    "stairway",
    "river",
    "bridge",
    "bookcase",
    "blind",
    "coffee table",
    "toilet",
    "flower",
    "book",
    "hill",
    "bench",
    "countertop",
    "stove",
    "palm",
    "kitchen island",
    "computer",
    "swivel chair",
    "boat",
    "bar",
    "arcade machine",
    "hovel",
    "bus",
    "towel",
    "light",
    "truck",
    "tower",
    "chandelier",
    "awning",
    "streetlight",
    "booth",
    "television receiver",
    "airplane",
    "dirt track",
    "apparel",
    "pole",
    "land",
    "bannister",
    "escalator",
    "ottoman",
    "bottle",
    "buffet",
    "poster",
    "stage",
    "van",
    "ship",
    "fountain",
    "conveyer belt",
    "canopy",
    "washer",
    "plaything",
    "swimming pool",
    "stool",
    "barrel",
    "basket",
    "waterfall",
    "tent",
    "bag",
    "minibike",
    "cradle",
    "oven",
    "ball",
    "food",
    "step",
    "tank",
    "trade name",
    "microwave",
    "pot",
    "animal",
    "bicycle",
    "lake",
    "dishwasher",
    "screen",
    "blanket",
    "sculpture",
    "hood",
    "sconce",
    "vase",
    "traffic light",
    "tray",
    "ashcan",
    "fan",
    "pier",
    "crt screen",
    "plate",
    "monitor",
    "bulletin board",
    "shower",
    "radiator",
    "glass",
    "clock",
    "flag",
]

OBJECTS365_CLASS_NAMES = [
    "person",
    "sneakers",
    "chair",
    "other shoes",
    "hat",
    "car",
    "lamp",
    "glasses",
    "bottle",
    "desk",
    "cup",
    "street lights",
    "cabinet (shelf)",
    "handbag (satchel)",
    "bracelet",
    "plate",
    "picture (frame)",
    "helmet",
    "book",
    "gloves",
    "storage box",
    "boat",
    "leather shoes",
    "flower",
    "bench",
    "potted plant",
    "bowl (basin)",
    "flag",
    "pillow",
    "boots",
    "vase",
    "microphone",
    "necklace",
    "ring",
    "suv",
    "wine glass",
    "belt",
    "monitor (tv)",
    "backpack",
    "umbrella",
    "traffic light",
    "speaker",
    "watch",
    "tie",
    "trash bin can",
    "slippers",
    "bicycle",
    "stool",
    "barrel (bucket)",
    "van",
    "couch",
    "sandals",
    "basket",
    "drum",
    "pen (pencil)",
    "bus",
    "wild bird",
    "high heels",
    "motorcycle",
    "guitar",
    "carpet",
    "cell phone",
    "bread",
    "camera",
    "canned",
    "truck",
    "traffic cone",
    "cymbal",
    "lifesaver",
    "towel",
    "stuffed toy",
    "candle",
    "sailboat",
    "laptop",
    "awning",
    "bed",
    "faucet",
    "tent",
    "horse",
    "mirror",
    "power outlet",
    "sink",
    "apple",
    "air conditioner",
    "knife",
    "hockey stick",
    "paddle",
    "pickup truck",
    "fork",
    "traffic sign",
    "balloon",
    "tripod",
    "dog",
    "spoon",
    "clock",
    "pot",
    "cow",
    "cake",
    "dinning table",
    "sheep",
    "hanger",
    "blackboard (whiteboard)",
    "napkin",
    "other fish",
    "orange (tangerine)",
    "toiletry",
    "keyboard",
    "tomato",
    "lantern",
    "machinery vehicle",
    "fan",
    "green vegetables",
    "banana",
    "baseball glove",
    "airplane",
    "mouse",
    "train",
    "pumpkin",
    "soccer",
    "skiboard",
    "luggage",
    "nightstand",
    "tea pot",
    "telephone",
    "trolley",
    "head phone",
    "sports car",
    "stop sign",
    "dessert",
    "scooter",
    "stroller",
    "crane",
    "remote",
    "refrigerator",
    "oven",
    "lemon",
    "duck",
    "baseball bat",
    "surveillance camera",
    "cat",
    "jug",
    "broccoli",
    "piano",
    "pizza",
    "elephant",
    "skateboard",
    "surfboard",
    "gun",
    "skating and skiing shoes",
    "gas stove",
    "donut",
    "bow tie",
    "carrot",
    "toilet",
    "kite",
    "strawberry",
    "other balls",
    "shovel",
    "pepper",
    "computer box",
    "toilet paper",
    "cleaning products",
    "chopsticks",
    "microwave",
    "pigeon",
    "baseball",
    "cutting (chopping board)",
    "coffee table",
    "side table",
    "scissors",
    "marker",
    "pie",
    "ladder",
    "snowboard",
    "cookies",
    "radiator",
    "fire hydrant",
    "basketball",
    "zebra",
    "grape",
    "giraffe",
    "potato",
    "sausage",
    "tricycle",
    "violin",
    "egg",
    "fire extinguisher",
    "candy",
    "fire truck",
    "billiards",
    "converter",
    "bathtub",
    "wheelchair",
    "golf club",
    "briefcase",
    "cucumber",
    "cigar (cigarette)",
    "paint brush",
    "pear",
    "heavy truck",
    "hamburger",
    "extractor",
    "extension cord",
    "tong",
    "tennis racket",
    "folder",
    "american football",
    "earphone",
    "mask",
    "kettle",
    "tennis",
    "ship",
    "swing",
    "coffee machine",
    "slide",
    "carriage",
    "onion",
    "green beans",
    "projector",
    "frisbee",
    "washing machine (drying machine)",
    "chicken",
    "printer",
    "watermelon",
    "saxophone",
    "tissue",
    "toothbrush",
    "ice cream",
    "hot-air balloon",
    "cello",
    "french fries",
    "scale",
    "trophy",
    "cabbage",
    "hot dog",
    "blender",
    "peach",
    "rice",
    "wallet (purse)",
    "volleyball",
    "deer",
    "goose",
    "tape",
    "tablet",
    "cosmetics",
    "trumpet",
    "pineapple",
    "golf ball",
    "ambulance",
    "parking meter",
    "mango",
    "key",
    "hurdle",
    "fishing rod",
    "medal",
    "flute",
    "brush",
    "penguin",
    "megaphone",
    "corn",
    "lettuce",
    "garlic",
    "swan",
    "helicopter",
    "green onion",
    "sandwich",
    "nuts",
    "speed limit sign",
    "induction cooker",
    "broom",
    "trombone",
    "plum",
    "rickshaw",
    "goldfish",
    "kiwi fruit",
    "router (modem)",
    "poker card",
    "toaster",
    "shrimp",
    "sushi",
    "cheese",
    "notepaper",
    "cherry",
    "pliers",
    "cd",
    "pasta",
    "hammer",
    "cue",
    "avocado",
    "hamimelon",
    "flask",
    "mushroom",
    "screwdriver",
    "soap",
    "recorder",
    "bear",
    "eggplant",
    "board eraser",
    "coconut",
    "tape measure (ruler)",
    "pig",
    "showerhead",
    "globe",
    "chips",
    "steak",
    "crosswalk sign",
    "stapler",
    "camel",
    "formula 1",
    "pomegranate",
    "dishwasher",
    "crab",
    "hoverboard",
    "meat ball",
    "rice cooker",
    "tuba",
    "calculator",
    "papaya",
    "antelope",
    "parrot",
    "seal",
    "butterfly",
    "dumbbell",
    "donkey",
    "lion",
    "urinal",
    "dolphin",
    "electric drill",
    "hair dryer",
    "egg tart",
    "jellyfish",
    "treadmill",
    "lighter",
    "grapefruit",
    "game board",
    "mop",
    "radish",
    "baozi",
    "target",
    "french",
    "spring rolls",
    "monkey",
    "rabbit",
    "pencil case",
    "yak",
    "red cabbage",
    "binoculars",
    "asparagus",
    "barbell",
    "scallop",
    "noddles",
    "comb",
    "dumpling",
    "oyster",
    "table tennis paddle",
    "cosmetics brush (eyeliner pencil)",
    "chainsaw",
    "eraser",
    "lobster",
    "durian",
    "okra",
    "lipstick",
    "cosmetics mirror",
    "curling",
    "table tennis",
]

OPEN_IMAGES_V4_BOXABLE_CLASS_NAMES = [
    "tortoise",
    "container",
    "magpie",
    "sea turtle",
    "football",
    "ambulance",
    "ladder",
    "toothbrush",
    "syringe",
    "sink",
    "toy",
    "organ",
    "cassette deck",
    "apple",
    "human eye",
    "cosmetics",
    "paddle",
    "snowman",
    "beer",
    "chopsticks",
    "human beard",
    "bird",
    "parking meter",
    "traffic light",
    "croissant",
    "cucumber",
    "radish",
    "towel",
    "doll",
    "skull",
    "washing machine",
    "glove",
    "tick",
    "belt",
    "sunglasses",
    "banjo",
    "cart",
    "ball",
    "backpack",
    "bicycle",
    "home appliance",
    "centipede",
    "boat",
    "surfboard",
    "boot",
    "headphones",
    "hot dog",
    "shorts",
    "fast food",
    "bus",
    "boy",
    "screwdriver",
    "bicycle wheel",
    "barge",
    "laptop",
    "miniskirt",
    "drill",
    "dress",
    "bear",
    "waffle",
    "pancake",
    "brown bear",
    "woodpecker",
    "blue jay",
    "pretzel",
    "bagel",
    "tower",
    "teapot",
    "person",
    "bow and arrow",
    "swimwear",
    "beehive",
    "brassiere",
    "bee",
    "bat",
    "starfish",
    "popcorn",
    "burrito",
    "chainsaw",
    "balloon",
    "wrench",
    "tent",
    "vehicle registration plate",
    "lantern",
    "toaster",
    "flashlight",
    "billboard",
    "tiara",
    "limousine",
    "necklace",
    "carnivore",
    "scissors",
    "stairs",
    "computer keyboard",
    "printer",
    "traffic sign",
    "chair",
    "shirt",
    "poster",
    "cheese",
    "sock",
    "fire hydrant",
    "land vehicle",
    "earrings",
    "tie",
    "watercraft",
    "cabinetry",
    "suitcase",
    "muffin",
    "bidet",
    "snack",
    "snowmobile",
    "clock",
    "medical equipment",
    "cattle",
    "cello",
    "jet ski",
    "camel",
    "coat",
    "suit",
    "desk",
    "cat",
    "bronze sculpture",
    "juice",
    "gondola",
    "beetle",
    "cannon",
    "computer mouse",
    "cookie",
    "office building",
    "fountain",
    "coin",
    "calculator",
    "cocktail",
    "computer monitor",
    "box",
    "stapler",
    "christmas tree",
    "cowboy hat",
    "hiking equipment",
    "studio couch",
    "drum",
    "dessert",
    "wine rack",
    "drink",
    "zucchini",
    "ladle",
    "human mouth",
    "dairy",
    "dice",
    "oven",
    "dinosaur",
    "ratchet",
    "couch",
    "cricket ball",
    "winter melon",
    "spatula",
    "whiteboard",
    "pencil sharpener",
    "door",
    "hat",
    "shower",
    "eraser",
    "fedora",
    "guacamole",
    "dagger",
    "scarf",
    "dolphin",
    "sombrero",
    "tin can",
    "mug",
    "tap",
    "harbor seal",
    "stretcher",
    "can opener",
    "goggles",
    "human body",
    "roller skates",
    "coffee cup",
    "cutting board",
    "blender",
    "plumbing fixture",
    "stop sign",
    "office supplies",
    "volleyball",
    "vase",
    "slow cooker",
    "wardrobe",
    "coffee",
    "whisk",
    "paper towel",
    "personal care",
    "food",
    "sun hat",
    "tree house",
    "flying disc",
    "skirt",
    "gas stove",
    "salt and pepper shakers",
    "mechanical fan",
    "face powder",
    "fax",
    "fruit",
    "french fries",
    "nightstand",
    "barrel",
    "kite",
    "tart",
    "treadmill",
    "fox",
    "flag",
    "horn",
    "window blind",
    "human foot",
    "golf cart",
    "jacket",
    "egg",
    "street light",
    "guitar",
    "pillow",
    "human leg",
    "isopod",
    "grape",
    "human ear",
    "power plugs and sockets",
    "panda",
    "giraffe",
    "woman",
    "door handle",
    "rhinoceros",
    "bathtub",
    "goldfish",
    "houseplant",
    "goat",
    "baseball bat",
    "baseball glove",
    "mixing bowl",
    "marine invertebrates",
    "kitchen utensil",
    "light switch",
    "house",
    "horse",
    "stationary bicycle",
    "hammer",
    "ceiling fan",
    "sofa bed",
    "adhesive tape",
    "harp",
    "sandal",
    "bicycle helmet",
    "saucer",
    "harpsichord",
    "human hair",
    "heater",
    "harmonica",
    "hamster",
    "curtain",
    "bed",
    "kettle",
    "fireplace",
    "scale",
    "drinking straw",
    "insect",
    "hair dryer",
    "kitchenware",
    "indoor rower",
    "invertebrate",
    "food processor",
    "bookcase",
    "refrigerator",
    "wood-burning stove",
    "punching bag",
    "common fig",
    "cocktail shaker",
    "jaguar",
    "golf ball",
    "fashion accessory",
    "alarm clock",
    "filing cabinet",
    "artichoke",
    "table",
    "tableware",
    "kangaroo",
    "koala",
    "knife",
    "bottle",
    "bottle opener",
    "lynx",
    "lavender",
    "lighthouse",
    "dumbbell",
    "human head",
    "bowl",
    "humidifier",
    "porch",
    "lizard",
    "billiard table",
    "mammal",
    "mouse",
    "motorcycle",
    "musical instrument",
    "swim cap",
    "frying pan",
    "snowplow",
    "bathroom cabinet",
    "missile",
    "bust",
    "man",
    "waffle iron",
    "milk",
    "ring binder",
    "plate",
    "mobile phone",
    "baked goods",
    "mushroom",
    "crutch",
    "pitcher",
    "mirror",
    "lifejacket",
    "table tennis racket",
    "pencil case",
    "musical keyboard",
    "scoreboard",
    "briefcase",
    "kitchen knife",
    "nail",
    "tennis ball",
    "plastic bag",
    "oboe",
    "chest of drawers",
    "ostrich",
    "piano",
    "girl",
    "plant",
    "potato",
    "hair spray",
    "sports equipment",
    "pasta",
    "penguin",
    "pumpkin",
    "pear",
    "infant bed",
    "polar bear",
    "mixer",
    "cupboard",
    "jacuzzi",
    "pizza",
    "digital clock",
    "pig",
    "reptile",
    "rifle",
    "lipstick",
    "skateboard",
    "raven",
    "high heels",
    "red panda",
    "rose",
    "rabbit",
    "sculpture",
    "saxophone",
    "shotgun",
    "seafood",
    "submarine sandwich",
    "snowboard",
    "sword",
    "picture frame",
    "sushi",
    "loveseat",
    "ski",
    "squirrel",
    "tripod",
    "stethoscope",
    "submarine",
    "scorpion",
    "segway",
    "training bench",
    "snake",
    "coffee table",
    "skyscraper",
    "sheep",
    "television",
    "trombone",
    "tea",
    "tank",
    "taco",
    "telephone",
    "torch",
    "tiger",
    "strawberry",
    "trumpet",
    "tree",
    "tomato",
    "train",
    "tool",
    "picnic basket",
    "cooking spray",
    "trousers",
    "bowling equipment",
    "football helmet",
    "truck",
    "measuring cup",
    "coffeemaker",
    "violin",
    "vehicle",
    "handbag",
    "paper cutter",
    "wine",
    "weapon",
    "wheel",
    "worm",
    "wok",
    "whale",
    "zebra",
    "auto part",
    "jug",
    "pizza cutter",
    "cream",
    "monkey",
    "lion",
    "bread",
    "platter",
    "chicken",
    "eagle",
    "helicopter",
    "owl",
    "duck",
    "turtle",
    "hippopotamus",
    "crocodile",
    "toilet",
    "toilet paper",
    "squid",
    "clothing",
    "footwear",
    "lemon",
    "spider",
    "deer",
    "frog",
    "banana",
    "rocket",
    "wine glass",
    "countertop",
    "tablet computer",
    "waste container",
    "swimming pool",
    "dog",
    "book",
    "elephant",
    "shark",
    "candle",
    "leopard",
    "axe",
    "hand dryer",
    "soap dispenser",
    "porcupine",
    "flower",
    "canary",
    "cheetah",
    "palm tree",
    "hamburger",
    "maple",
    "building",
    "fish",
    "lobster",
    "asparagus",
    "furniture",
    "hedgehog",
    "airplane",
    "spoon",
    "otter",
    "bull",
    "oyster",
    "horizontal bar",
    "convenience store",
    "bomb",
    "bench",
    "ice cream",
    "caterpillar",
    "butterfly",
    "parachute",
    "orange",
    "antelope",
    "beaker",
    "moths and butterflies",
    "window",
    "closet",
    "castle",
    "jellyfish",
    "goose",
    "mule",
    "swan",
    "peach",
    "coconut",
    "seat belt",
    "raccoon",
    "chisel",
    "fork",
    "lamp",
    "camera",
    "squash",
    "racket",
    "human face",
    "human arm",
    "vegetable",
    "diaper",
    "unicycle",
    "falcon",
    "chime",
    "snail",
    "shellfish",
    "cabbage",
    "carrot",
    "mango",
    "jeans",
    "flowerpot",
    "pineapple",
    "drawer",
    "stool",
    "envelope",
    "cake",
    "dragonfly",
    "sunflower",
    "microwave oven",
    "honeycomb",
    "marine mammal",
    "sea lion",
    "ladybug",
    "shelf",
    "watch",
    "candy",
    "salad",
    "parrot",
    "handgun",
    "sparrow",
    "van",
    "grinder",
    "spice rack",
    "light bulb",
    "corded phone",
    "sports uniform",
    "tennis racket",
    "wall clock",
    "serving tray",
    "kitchen & dining room table",
    "dog bed",
    "cake stand",
    "cat furniture",
    "bathroom accessory",
    "facial tissue holder",
    "pressure cooker",
    "kitchen appliance",
    "tire",
    "ruler",
    "luggage and bags",
    "microphone",
    "broccoli",
    "umbrella",
    "pastry",
    "grapefruit",
    "band-aid",
    "animal",
    "bell pepper",
    "turkey",
    "lily",
    "pomegranate",
    "doughnut",
    "glasses",
    "human nose",
    "pen",
    "ant",
    "car",
    "aircraft",
    "human hand",
    "skunk",
    "teddy bear",
    "watermelon",
    "cantaloupe",
    "dishwasher",
    "flute",
    "balance beam",
    "sandwich",
    "shrimp",
    "sewing machine",
    "binoculars",
    "rays and skates",
    "ipod",
    "accordion",
    "willow",
    "crab",
    "crown",
    "seahorse",
    "perfume",
    "alpaca",
    "taxi",
    "canoe",
    "remote control",
    "wheelchair",
    "rugby ball",
    "armadillo",
    "maracas",
    "helmet",
]

VISUAL_GENOME_CLASS_NAMES = [
    "yolk",
    "goal",
    "bathroom",
    "macaroni",
    "umpire",
    "toothpick",
    "alarm clock",
    "ceiling fan",
    "photos",
    "parrot",
    "tail fin",
    "birthday cake",
    "calculator",
    "catcher",
    "toilet",
    "batter",
    "stop sign",
    "stopsign",
    "cone",
    "microwave",
    "microwave oven",
    "skateboard ramp",
    "tea",
    "dugout",
    "products",
    "halter",
    "kettle",
    "kitchen",
    "refrigerator",
    "fridge",
    "ostrich",
    "bathtub",
    "blinds",
    "court",
    "urinal",
    "knee pads",
    "bed",
    "flamingo",
    "giraffe",
    "helmet",
    "giraffes",
    "tennis court",
    "motorcycle",
    "laptop",
    "tea pot",
    "horse",
    "television",
    "tv",
    "shorts",
    "manhole",
    "dishwasher",
    "jeans",
    "sail",
    "monitor",
    "man",
    "shirt",
    "car",
    "cat",
    "garage door",
    "bus",
    "radiator",
    "tights",
    "sailboat",
    "sail boat",
    "racket",
    "racquet",
    "plate",
    "rock wall",
    "beach",
    "trolley",
    "ocean",
    "headboard",
    "head board",
    "tea kettle",
    "wetsuit",
    "tennis racket",
    "tennis racquet",
    "sink",
    "train",
    "keyboard",
    "sky",
    "match",
    "train station",
    "stereo",
    "bats",
    "tennis player",
    "toilet brush",
    "lighter",
    "pepper shaker",
    "gazebo",
    "hair dryer",
    "elephant",
    "toilet seat",
    "zebra",
    "skateboard",
    "skate board",
    "zebras",
    "floor lamp",
    "french fries",
    "woman",
    "player",
    "tower",
    "bicycle",
    "magazines",
    "christmas tree",
    "umbrella",
    "cow",
    "pants",
    "bike",
    "field",
    "living room",
    "latch",
    "bedroom",
    "grape",
    "castle",
    "table",
    "swan",
    "blender",
    "orange",
    "teddy bear",
    "net",
    "meter",
    "baseball field",
    "runway",
    "screen",
    "ski boot",
    "dog",
    "clock",
    "hair",
    "avocado",
    "highway",
    "skirt",
    "frisbee",
    "parasail",
    "desk",
    "pizza",
    "mouse",
    "sign",
    "shower curtain",
    "polar bear",
    "airplane",
    "jersey",
    "reigns",
    "hot dog",
    "hotdog",
    "surfboard",
    "surf board",
    "couch",
    "glass",
    "snowboard",
    "girl",
    "plane",
    "elephants",
    "oven",
    "dirt bike",
    "tail wing",
    "area rug",
    "bear",
    "washer",
    "date",
    "bow tie",
    "cows",
    "fire extinguisher",
    "bamboo",
    "wallet",
    "tail feathers",
    "truck",
    "beach chair",
    "boat",
    "tablet",
    "ceiling",
    "chandelier",
    "sheep",
    "glasses",
    "ram",
    "kite",
    "salad",
    "pillow",
    "fire hydrant",
    "hydrant",
    "mug",
    "tarmac",
    "computer",
    "swimsuit",
    "tomato",
    "tire",
    "cauliflower",
    "fireplace",
    "snow",
    "building",
    "sandwich",
    "weather vane",
    "bird",
    "jacket",
    "chair",
    "water",
    "cats",
    "soccer ball",
    "horses",
    "drapes",
    "barn",
    "engine",
    "cake",
    "head",
    "head band",
    "skier",
    "town",
    "bath tub",
    "bowl",
    "stove",
    "tongue",
    "coffee table",
    "floor",
    "uniform",
    "ottoman",
    "broccoli",
    "olive",
    "mound",
    "pitcher",
    "food",
    "paintings",
    "traffic light",
    "parking meter",
    "bananas",
    "mountain",
    "cage",
    "hedge",
    "motorcycles",
    "wet suit",
    "radish",
    "teddy bears",
    "monitors",
    "suitcase",
    "suit case",
    "drawers",
    "grass",
    "apple",
    "lamp",
    "goggles",
    "boy",
    "armchair",
    "ramp",
    "burner",
    "lamb",
    "cup",
    "tank top",
    "boats",
    "hat",
    "soup",
    "fence",
    "necklace",
    "visor",
    "coffee",
    "bottle",
    "stool",
    "shoe",
    "surfer",
    "stop",
    "backpack",
    "shin guard",
    "wii remote",
    "wall",
    "pizza slice",
    "home plate",
    "van",
    "packet",
    "earrings",
    "wristband",
    "tracks",
    "mitt",
    "dome",
    "snowboarder",
    "faucet",
    "toiletries",
    "ski boots",
    "room",
    "fork",
    "snow suit",
    "banana slice",
    "bench",
    "tie",
    "burners",
    "stuffed animals",
    "zoo",
    "train platform",
    "cupcake",
    "curtain",
    "ear",
    "tissue box",
    "bread",
    "scissors",
    "vase",
    "herd",
    "smoke",
    "skylight",
    "cub",
    "tail",
    "cutting board",
    "wave",
    "hedges",
    "windshield",
    "apples",
    "mirror",
    "license plate",
    "tree",
    "wheel",
    "ski pole",
    "clock tower",
    "freezer",
    "luggage",
    "skateboarder",
    "mousepad",
    "road",
    "bat",
    "toilet tank",
    "vanity",
    "neck",
    "cliff",
    "tub",
    "sprinkles",
    "dresser",
    "street",
    "wing",
    "suit",
    "veggie",
    "palm trees",
    "urinals",
    "door",
    "propeller",
    "keys",
    "skate park",
    "platform",
    "pot",
    "towel",
    "computer monitor",
    "flip flop",
    "eggs",
    "shed",
    "moped",
    "sand",
    "face",
    "scissor",
    "carts",
    "squash",
    "pillows",
    "family",
    "glove",
    "rug",
    "watch",
    "grafitti",
    "dogs",
    "scoreboard",
    "basket",
    "poster",
    "duck",
    "horns",
    "bears",
    "jeep",
    "painting",
    "lighthouse",
    "remote control",
    "toaster",
    "vegetables",
    "surfboards",
    "ducks",
    "lane",
    "carrots",
    "market",
    "paper towels",
    "island",
    "blueberries",
    "smile",
    "balloons",
    "stroller",
    "napkin",
    "towels",
    "papers",
    "person",
    "train tracks",
    "child",
    "headband",
    "pool",
    "plant",
    "harbor",
    "counter",
    "hand",
    "house",
    "donut",
    "doughnut",
    "knot",
    "soccer player",
    "seagull",
    "bottles",
    "buses",
    "coat",
    "trees",
    "geese",
    "bun",
    "toilet bowl",
    "trunk",
    "station",
    "bikini",
    "goatee",
    "lounge chair",
    "breakfast",
    "nose",
    "moon",
    "river",
    "racer",
    "picture",
    "shaker",
    "sidewalk",
    "side walk",
    "shutters",
    "stove top",
    "stovetop",
    "church",
    "lampshade",
    "map",
    "shop",
    "platter",
    "airport",
    "hoodie",
    "oranges",
    "woods",
    "enclosure",
    "skatepark",
    "vases",
    "city",
    "park",
    "mailbox",
    "balloon",
    "billboard",
    "pasture",
    "portrait",
    "forehead",
    "ship",
    "cookie",
    "seaweed",
    "sofa",
    "slats",
    "tomato slice",
    "tractor",
    "bull",
    "suitcases",
    "graffiti",
    "policeman",
    "remotes",
    "pens",
    "window sill",
    "suspenders",
    "easel",
    "tray",
    "straw",
    "collar",
    "shower",
    "bag",
    "scooter",
    "tails",
    "toilet lid",
    "panda",
    "comforter",
    "outlet",
    "stems",
    "valley",
    "flag",
    "jockey",
    "gravel",
    "mouth",
    "window",
    "bridge",
    "corn",
    "mountains",
    "beer",
    "pitcher's mound",
    "palm tree",
    "crowd",
    "skis",
    "phone",
    "banana bunch",
    "tennis shoe",
    "ground",
    "carpet",
    "eye",
    "urn",
    "beak",
    "giraffe head",
    "steeple",
    "mattress",
    "baseball player",
    "wine",
    "water bottle",
    "kitten",
    "archway",
    "candle",
    "croissant",
    "tennis ball",
    "dress",
    "column",
    "utensils",
    "cell phone",
    "computer mouse",
    "cap",
    "lawn",
    "airplanes",
    "carriage",
    "snout",
    "cabinets",
    "lemons",
    "grill",
    "umbrellas",
    "meat",
    "wagon",
    "ipod",
    "bookshelf",
    "cart",
    "roof",
    "hay",
    "ski pants",
    "seat",
    "mane",
    "bikes",
    "drawer",
    "game",
    "clock face",
    "boys",
    "rider",
    "fire escape",
    "slope",
    "iphone",
    "pumpkin",
    "pan",
    "chopsticks",
    "hill",
    "uniforms",
    "cleat",
    "costume",
    "cabin",
    "police officer",
    "ears",
    "egg",
    "trash can",
    "horn",
    "arrow",
    "toothbrush",
    "carrot",
    "banana",
    "planes",
    "garden",
    "forest",
    "brocolli",
    "aircraft",
    "front window",
    "dashboard",
    "statue",
    "saucer",
    "people",
    "silverware",
    "fruit",
    "drain",
    "jet",
    "speaker",
    "eyes",
    "railway",
    "lid",
    "soap",
    "rocks",
    "office chair",
    "door knob",
    "banana peel",
    "baseball game",
    "asparagus",
    "spoon",
    "cabinet door",
    "pineapple",
    "traffic cone",
    "nightstand",
    "night stand",
    "teapot",
    "taxi",
    "chimney",
    "lake",
    "suit jacket",
    "train engine",
    "ball",
    "wrist band",
    "pickle",
    "fruits",
    "pad",
    "dispenser",
    "bridle",
    "breast",
    "cones",
    "headlight",
    "necktie",
    "skater",
    "toilet paper",
    "skyscraper",
    "telephone",
    "ox",
    "roadway",
    "sock",
    "paddle",
    "dishes",
    "hills",
    "street sign",
    "headlights",
    "benches",
    "fuselage",
    "card",
    "napkins",
    "bush",
    "rice",
    "computer screen",
    "spokes",
    "flowers",
    "bucket",
    "rock",
    "pole",
    "pear",
    "sauce",
    "store",
    "juice",
    "knobs",
    "mustard",
    "ski",
    "stands",
    "cabinet",
    "dirt",
    "goats",
    "wine glass",
    "spectators",
    "crate",
    "pancakes",
    "kids",
    "engines",
    "shade",
    "feeder",
    "cellphone",
    "pepper",
    "blanket",
    "sunglasses",
    "train car",
    "magnet",
    "donuts",
    "doughnuts",
    "sweater",
    "signal",
    "advertisement",
    "log",
    "vent",
    "whiskers",
    "adult",
    "arch",
    "locomotive",
    "tennis match",
    "tent",
    "motorbike",
    "magnets",
    "night",
    "marina",
    "wool",
    "vest",
    "railroad tracks",
    "stuffed bear",
    "moustache",
    "bib",
    "frame",
    "snow pants",
    "tank",
    "undershirt",
    "icons",
    "neck tie",
    "beams",
    "baseball bat",
    "safety cone",
    "paper towel",
    "bedspread",
    "can",
    "container",
    "flower",
    "vehicle",
    "tomatoes",
    "back wheel",
    "soccer field",
    "nostril",
    "suv",
    "buildings",
    "canopy",
    "flame",
    "kid",
    "baseball",
    "throw pillow",
    "belt",
    "rainbow",
    "lemon",
    "oven door",
    "tag",
    "books",
    "monument",
    "men",
    "shadow",
    "bicycles",
    "cars",
    "lamp shade",
    "pine tree",
    "bouquet",
    "toothpaste",
    "potato",
    "sinks",
    "hook",
    "switch",
    "lamp post",
    "lamppost",
    "lapel",
    "desert",
    "knob",
    "chairs",
    "pasta",
    "feathers",
    "hole",
    "meal",
    "station wagon",
    "kites",
    "boots",
    "baby",
    "biker",
    "gate",
    "signal light",
    "headphones",
    "goat",
    "waves",
    "bumper",
    "bud",
    "logo",
    "curtains",
    "american flag",
    "yacht",
    "box",
    "baseball cap",
    "fries",
    "controller",
    "awning",
    "path",
    "front legs",
    "life jacket",
    "purse",
    "outfield",
    "pigeon",
    "toddler",
    "beard",
    "thumb",
    "water tank",
    "board",
    "parade",
    "robe",
    "newspaper",
    "wires",
    "camera",
    "pastries",
    "deck",
    "watermelon",
    "clouds",
    "deer",
    "motorcyclist",
    "kneepad",
    "sneakers",
    "women",
    "onions",
    "eyebrow",
    "gas station",
    "vane",
    "girls",
    "trash",
    "numerals",
    "knife",
    "tags",
    "light",
    "bunch",
    "outfit",
    "groom",
    "infield",
    "frosting",
    "forks",
    "entertainment center",
    "stuffed animal",
    "yard",
    "numeral",
    "ladder",
    "shoes",
    "bracelet",
    "teeth",
    "guy",
    "display case",
    "cushion",
    "post",
    "pathway",
    "tablecloth",
    "skiers",
    "trouser",
    "cloud",
    "hands",
    "produce",
    "beam",
    "ketchup",
    "paw",
    "dish",
    "raft",
    "crosswalk",
    "front wheel",
    "toast",
    "cattle",
    "players",
    "group",
    "coffee pot",
    "track",
    "cowboy hat",
    "petal",
    "eyeglasses",
    "handle",
    "table cloth",
    "jets",
    "shakers",
    "remote",
    "snowsuit",
    "bushes",
    "dessert",
    "leg",
    "eagle",
    "fire truck",
    "firetruck",
    "game controller",
    "smartphone",
    "backsplash",
    "trains",
    "shore",
    "signs",
    "bell",
    "cupboards",
    "sweat band",
    "sack",
    "ankle",
    "coin slot",
    "bagel",
    "masts",
    "police",
    "drawing",
    "biscuit",
    "toy",
    "legs",
    "pavement",
    "outside",
    "wheels",
    "driver",
    "numbers",
    "blazer",
    "pen",
    "cabbage",
    "trucks",
    "key",
    "saddle",
    "pillow case",
    "goose",
    "label",
    "boulder",
    "pajamas",
    "wrist",
    "shelf",
    "cross",
    "coffee cup",
    "foliage",
    "lot",
    "fry",
    "air",
    "officer",
    "pepperoni",
    "cheese",
    "lady",
    "kickstand",
    "counter top",
    "veggies",
    "baseball uniform",
    "book shelf",
    "bags",
    "pickles",
    "stand",
    "netting",
    "lettuce",
    "facial hair",
    "lime",
    "animals",
    "drape",
    "boot",
    "railing",
    "end table",
    "shin guards",
    "steps",
    "trashcan",
    "tusk",
    "head light",
    "walkway",
    "cockpit",
    "tennis net",
    "animal",
    "boardwalk",
    "keypad",
    "bookcase",
    "blueberry",
    "trash bag",
    "ski poles",
    "parking lot",
    "gas tank",
    "beds",
    "fan",
    "base",
    "soap dispenser",
    "banner",
    "life vest",
    "train front",
    "word",
    "cab",
    "liquid",
    "exhaust pipe",
    "sneaker",
    "light fixture",
    "power lines",
    "curb",
    "scene",
    "buttons",
    "roman numerals",
    "muzzle",
    "sticker",
    "bacon",
    "pizzas",
    "paper",
    "feet",
    "stairs",
    "triangle",
    "plants",
    "rope",
    "beans",
    "brim",
    "beverage",
    "letters",
    "soda",
    "menu",
    "finger",
    "dvds",
    "candles",
    "picnic table",
    "wine bottle",
    "pencil",
    "tree trunk",
    "nail",
    "mantle",
    "countertop",
    "view",
    "line",
    "motor bike",
    "audience",
    "traffic sign",
    "arm",
    "pedestrian",
    "stabilizer",
    "dock",
    "doorway",
    "bedding",
    "end",
    "worker",
    "canal",
    "crane",
    "grate",
    "little girl",
    "rims",
    "passenger car",
    "plates",
    "background",
    "peel",
    "brake light",
    "roman numeral",
    "string",
    "tines",
    "turf",
    "armrest",
    "shower head",
    "leash",
    "stones",
    "stoplight",
    "handle bars",
    "front",
    "scarf",
    "band",
    "jean",
    "tennis",
    "pile",
    "doorknob",
    "foot",
    "houses",
    "windows",
    "restaurant",
    "booth",
    "cardboard box",
    "fingers",
    "mountain range",
    "bleachers",
    "rail",
    "pastry",
    "canoe",
    "sun",
    "eye glasses",
    "salt shaker",
    "number",
    "fish",
    "knee pad",
    "fur",
    "she",
    "shower door",
    "rod",
    "branches",
    "birds",
    "printer",
    "sunset",
    "median",
    "shutter",
    "slice",
    "heater",
    "prongs",
    "bathing suit",
    "skiier",
    "rack",
    "book",
    "blade",
    "apartment",
    "manhole cover",
    "stools",
    "overhang",
    "door handle",
    "couple",
    "picture frame",
    "chicken",
    "planter",
    "seats",
    "hour hand",
    "dvd player",
    "ski slope",
    "french fry",
    "bowls",
    "top",
    "landing gear",
    "coffee maker",
    "melon",
    "computers",
    "light switch",
    "jar",
    "tv stand",
    "overalls",
    "garage",
    "tabletop",
    "writing",
    "doors",
    "stadium",
    "placemat",
    "air vent",
    "trick",
    "sled",
    "mast",
    "pond",
    "steering wheel",
    "baseball glove",
    "watermark",
    "pie",
    "sandwhich",
    "cpu",
    "mushroom",
    "power pole",
    "dirt road",
    "handles",
    "speakers",
    "fender",
    "telephone pole",
    "strawberry",
    "mask",
    "children",
    "crust",
    "art",
    "rim",
    "branch",
    "display",
    "grasses",
    "photo",
    "receipt",
    "instructions",
    "herbs",
    "toys",
    "handlebars",
    "trailer",
    "sandal",
    "skull",
    "hangar",
    "pipe",
    "office",
    "chest",
    "lamps",
    "horizon",
    "calendar",
    "foam",
    "stone",
    "bars",
    "button",
    "poles",
    "heart",
    "hose",
    "jet engine",
    "potatoes",
    "rain",
    "magazine",
    "chain",
    "footboard",
    "tee shirt",
    "design",
    "walls",
    "copyright",
    "pictures",
    "pillar",
    "drink",
    "barrier",
    "boxes",
    "chocolate",
    "chef",
    "slot",
    "sweatpants",
    "face mask",
    "icing",
    "wipers",
    "circle",
    "bin",
    "kitty",
    "electronics",
    "wild",
    "tiles",
    "steam",
    "lettering",
    "bathroom sink",
    "laptop computer",
    "cherry",
    "spire",
    "conductor",
    "sheet",
    "slab",
    "windshield wipers",
    "storefront",
    "hill side",
    "spatula",
    "tail light",
    "taillight",
    "bean",
    "wire",
    "intersection",
    "pier",
    "snow board",
    "trunks",
    "website",
    "bolt",
    "kayak",
    "nuts",
    "holder",
    "turbine",
    "stop light",
    "olives",
    "ball cap",
    "burger",
    "barrel",
    "fans",
    "beanie",
    "stem",
    "lines",
    "traffic signal",
    "sweatshirt",
    "handbag",
    "mulch",
    "socks",
    "landscape",
    "soda can",
    "shelves",
    "ski lift",
    "cord",
    "vegetable",
    "apron",
    "blind",
    "bracelets",
    "stickers",
    "traffic",
    "strip",
    "tennis shoes",
    "swim trunks",
    "hillside",
    "sandals",
    "concrete",
    "lips",
    "butter knife",
    "words",
    "leaves",
    "train cars",
    "spoke",
    "cereal",
    "pine trees",
    "cooler",
    "bangs",
    "half",
    "sheets",
    "figurine",
    "park bench",
    "stack",
    "second floor",
    "motor",
    "hand towel",
    "wristwatch",
    "spectator",
    "tissues",
    "flip flops",
    "quilt",
    "floret",
    "calf",
    "back pack",
    "grapes",
    "ski tracks",
    "skin",
    "bow",
    "controls",
    "dinner",
    "baseball players",
    "ad",
    "ribbon",
    "hotel",
    "sea",
    "cover",
    "tarp",
    "weather",
    "notebook",
    "mustache",
    "stone wall",
    "closet",
    "statues",
    "bank",
    "skateboards",
    "butter",
    "dress shirt",
    "knee",
    "wood",
    "laptops",
    "cuff",
    "hubcap",
    "wings",
    "range",
    "structure",
    "balls",
    "tunnel",
    "globe",
    "utensil",
    "dumpster",
    "cd",
    "floors",
    "wrapper",
    "folder",
    "pocket",
    "mother",
    "ski goggles",
    "posts",
    "power line",
    "wake",
    "roses",
    "train track",
    "reflection",
    "air conditioner",
    "referee",
    "barricade",
    "baseball mitt",
    "mouse pad",
    "garbage can",
    "buckle",
    "footprints",
    "lights",
    "muffin",
    "bracket",
    "plug",
    "taxi cab",
    "drinks",
    "surfers",
    "arrows",
    "control panel",
    "ring",
    "twigs",
    "soil",
    "skies",
    "clock hand",
    "caboose",
    "playground",
    "mango",
    "stump",
    "brick wall",
    "screw",
    "minivan",
    "leaf",
    "fencing",
    "ledge",
    "clothes",
    "grass field",
    "plumbing",
    "blouse",
    "patch",
    "scaffolding",
    "hamburger",
    "utility pole",
    "teddy",
    "rose",
    "skillet",
    "cycle",
    "cable",
    "gloves",
    "bark",
    "decoration",
    "tables",
    "palm",
    "wii",
    "mountain top",
    "shrub",
    "hoof",
    "celery",
    "beads",
    "plaque",
    "flooring",
    "surf",
    "cloth",
    "passenger",
    "spot",
    "plastic",
    "knives",
    "case",
    "railroad",
    "pony",
    "muffler",
    "hot dogs",
    "hotdogs",
    "stripe",
    "scale",
    "block",
    "recliner",
    "body",
    "shades",
    "tap",
    "tools",
    "cupboard",
    "wallpaper",
    "sculpture",
    "surface",
    "sedan",
    "distance",
    "shrubs",
    "skiis",
    "lift",
    "bottom",
    "cleats",
    "roll",
    "clothing",
    "bed frame",
    "slacks",
    "tail lights",
    "doll",
    "traffic lights",
    "symbol",
    "strings",
    "fixtures",
    "short",
    "paint",
    "candle holder",
    "guard rail",
    "cyclist",
    "tree branches",
    "ripples",
    "gear",
    "waist",
    "trash bin",
    "onion",
    "home",
    "side mirror",
    "brush",
    "sweatband",
    "handlebar",
    "light pole",
    "street lamp",
    "pads",
    "ham",
    "artwork",
    "reflector",
    "figure",
    "tile",
    "mountainside",
    "black",
    "bricks",
    "paper plate",
    "stick",
    "beef",
    "patio",
    "weeds",
    "back",
    "sausage",
    "paws",
    "farm",
    "decal",
    "harness",
    "monkey",
    "fence post",
    "door frame",
    "stripes",
    "clocks",
    "ponytail",
    "toppings",
    "strap",
    "carton",
    "greens",
    "chin",
    "lunch",
    "name",
    "earring",
    "area",
    "tshirt",
    "t-shirt",
    "t shirt",
    "cream",
    "rails",
    "cushions",
    "lanyard",
    "brick",
    "hallway",
    "cucumber",
    "wire fence",
    "fern",
    "tangerine",
    "windowsill",
    "pipes",
    "package",
    "wheelchair",
    "chips",
    "driveway",
    "tattoo",
    "side window",
    "stairway",
    "basin",
    "machine",
    "table lamp",
    "radio",
    "pony tail",
    "ocean water",
    "inside",
    "cargo",
    "overpass",
    "mat",
    "socket",
    "flower pot",
    "tree line",
    "sign post",
    "tube",
    "dial",
    "splash",
    "male",
    "lantern",
    "lipstick",
    "lip",
    "tongs",
    "ski suit",
    "trail",
    "passenger train",
    "bandana",
    "antelope",
    "designs",
    "tents",
    "photograph",
    "catcher's mitt",
    "electrical outlet",
    "tires",
    "boulders",
    "mannequin",
    "plain",
    "layer",
    "mushrooms",
    "strawberries",
    "piece",
    "oar",
    "bike rack",
    "slices",
    "arms",
    "fin",
    "shadows",
    "hood",
    "windshield wiper",
    "letter",
    "dot",
    "bus stop",
    "railings",
    "pebbles",
    "mud",
    "claws",
    "police car",
    "crown",
    "meters",
    "name tag",
    "entrance",
    "staircase",
    "shrimp",
    "ladies",
    "peak",
    "vines",
    "computer keyboard",
    "glass door",
    "pears",
    "pant",
    "wine glasses",
    "stall",
    "asphalt",
    "columns",
    "sleeve",
    "pack",
    "cheek",
    "baskets",
    "land",
    "day",
    "blocks",
    "courtyard",
    "pedal",
    "panel",
    "seeds",
    "balcony",
    "yellow",
    "disc",
    "young man",
    "eyebrows",
    "crumbs",
    "spinach",
    "emblem",
    "object",
    "bar",
    "cardboard",
    "tissue",
    "light post",
    "ski jacket",
    "seasoning",
    "parasol",
    "terminal",
    "surfing",
    "streetlight",
    "street light",
    "alley",
    "cords",
    "image",
    "jug",
    "antenna",
    "puppy",
    "berries",
    "diamond",
    "pans",
    "fountain",
    "foreground",
    "syrup",
    "bride",
    "spray",
    "license",
    "peppers",
    "passengers",
    "cement",
    "flags",
    "shack",
    "trough",
    "objects",
    "arches",
    "streamer",
    "pots",
    "border",
    "baseboard",
    "beer bottle",
    "wrist watch",
    "tile floor",
    "page",
    "pin",
    "items",
    "baseline",
    "hanger",
    "tree branch",
    "tusks",
    "donkey",
    "containers",
    "condiments",
    "device",
    "envelope",
    "parachute",
    "mesh",
    "hut",
    "butterfly",
    "salt",
    "restroom",
    "twig",
    "pilot",
    "ivy",
    "furniture",
    "clay",
    "print",
    "sandwiches",
    "lion",
    "shingles",
    "pillars",
    "vehicles",
    "panes",
    "shoreline",
    "stream",
    "control",
    "lock",
    "microphone",
    "blades",
    "towel rack",
    "coaster",
    "star",
    "petals",
    "text",
    "feather",
    "spots",
    "buoy",
]

skip_phrase_list = ['background', 'scene', 'object', 'image', 'element', 'text', 'landscape', 'setting', 'space', 'foreground', 'life', 'backdrop', 'nature', 'design', 'atmosphere', 'surface', 'position', 'structure', 'hue', 'picture', 'color', 'frame', 'charm', 'area', 'attention', 'presence', 'attire', 'surroundings', 'word', 'world', 'distance', 'location', 'ambiance', 'gaze', 'tone', 'figure', 'field', 'center', 'day', 'air', 'pattern', 'tranquility', 'view', 'photo', 'story', 'activity', 'expression', 'item', 'time', 'composition', 'viewer', 'environment', 'horizon', 'moment', 'narrative', 'ground', 'place', 'spectator', 'architecture', 'texture', 'anticipation', 'content', 'detail', 'back', 'cityscape', 'motion', 'top', 'comfort', 'display', 'journey', 'description', 'action', 'atmosphäre', 'expanse', 'water', 'glow', 'adventure', 'individual', 'joy', 'city life', 'interior', 'character', 'night', 'angle', 'perspective', 'stance', 'history', 'shape', 'energy', 'spirit', 'match', 'movement', 'game', 'exterior', 'beauty', 'event', 'accent', 'focus', 'bustle', 'touch', 'camaraderie', 'aesthetic', 'vantage point', 'excitement', 'direction', 'warmth', 'harmony', 'border', 'right', 'terrain', 'mid-air', 'palette', 'message', 'interaction', 'workspace', 'spectacle', 'base', 'name', 'theme', 'mood', 'solitude', 'left', 'culture', 'grandeur', 'facade', 'boundary', 'white', 'information', 'illustration', 'row', 'balance', 'creativity', 'layout', 'style', 'simplicity', 'body language', 'photograph', 'celebration', 'hustle', 'work', 'form', 'court', 'edge', 'chaos', 'posture', 'elegance', 'handle', 'tableau', 'short', 'clothing', 'context', 'depth', 'uniform', 'rhythm', 'everyday life', 'experience', 'reflection', 'identity', 'pleasure', 'marvel', 'weather', 'neighborhood', 'track', 'urban life', 'functionality', 'silhouette', 'aura', 'pose', 'outdoors', 'conversation', 'imagination', 'surrounding', 'countertop', 'serenity', 'side', 'scenery', 'atmosfere', 'peak', 'traffic', 'arrangement', 'mystery', 'thrill', 'essence', 'formation', 'skill', 'outline', 'presentation', 'community', 'group', 'it', 'he', 'she', 'they']
